#######################################################################################################################
##                                                 SERVER                                                            ##
#######################################################################################################################

server:
  port: 8085

#######################################################################################################################
##                                               APPLICATION                                                         ##
#######################################################################################################################

application:
  cors:
    allowedHeaders: 'Content-Type, Accept, Authorization, X-Requested-With'
    allowedMethods: 'GET,POST,OPTIONS,DELETE,PUT'
    allowedOrigins: '*'
    maxAge: 3600
  widgets:
    repository: '/tmp'
